services:
  animais-database:
    image: postgres:18.3
    environment:
      POSTGRES_DB: animaisdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5434:5432"
    volumes:
      - animais_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d animaisdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  animais_data: